import {attentionMessage,buildOrdersQuery,money,orderStatusLabel,paymentStatusLabel} from "./orders-model.js";
const $=s=>document.querySelector(s);const panel=$("#ordersPanel"),list=$("#ordersList"),detail=$("#orderDetail"),message=$("#ordersMessage");let cursor=null;
function say(text){message.textContent=text||"";message.hidden=!text}
async function api(path){const r=await fetch(path,{credentials:"same-origin"});if(r.status===401){say("Your session expired. Sign in again.");return null}const b=await r.json().catch(()=>null);if(!r.ok){say("Orders are temporarily unavailable. Try again.");return null}return b}
function card(order){const a=document.createElement("article");a.className="product-card order-card";a.tabIndex=0;const title=document.createElement("h3");title.textContent=order.order_number;const p=document.createElement("p");p.textContent=[order.customer_name||"Customer unavailable",money(order.total,order.currency),paymentStatusLabel(order.payment_status),orderStatusLabel(order.order_status)].join(" · ");a.append(title,p);const attention=attentionMessage(order.reason);if(attention){const w=document.createElement("p");w.className="card-warning";w.textContent=attention;a.append(w)}a.addEventListener("click",()=>openDetail(order.id));a.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openDetail(order.id)}});return a}
async function load(){const q=buildOrdersQuery({search:$("#ordersSearch").value,order_status:$("#orderStatusFilter").value,payment_status:$("#paymentStatusFilter").value,attention:$("#attentionFilter").value,limit:25,cursor});const body=await api("/api/orders?"+q);if(!body)return;list.replaceChildren(...body.orders.map(card));cursor=body.next_cursor;$("#ordersMore").hidden=!cursor;say(body.orders.length?"":"No orders match these filters.")}
async function openDetail(id){const body=await api("/api/orders/"+encodeURIComponent(id));if(!body)return;const o=body.order;detail.hidden=false;$("#orderDetailTitle").textContent=o.order_number;$("#orderDetailBody").replaceChildren();const facts=[["Payment",paymentStatusLabel(o.payment_status)],["Order",orderStatusLabel(o.order_status)],["Customer",o.customer?.name],["Email",o.customer?.email],["Phone",o.customer?.phone],["Shipping",o.shipping_address?[o.shipping_address.name,o.shipping_address.line1,o.shipping_address.line2,o.shipping_address.city,o.shipping_address.state,o.shipping_address.postal_code,o.shipping_address.country].filter(Boolean).join(", "):null],["Subtotal",money(o.subtotal,o.currency)],["Tax",money(o.tax,o.currency)],["Shipping",money(o.shipping,o.currency)],["Total",money(o.total,o.currency)]];for(const [k,v]of facts){if(v){const p=document.createElement("p");p.textContent=k+": "+v;$("#orderDetailBody").append(p)}}const h=document.createElement("h3");h.textContent="Items";$("#orderDetailBody").append(h);for(const item of o.items||[]){const p=document.createElement("p");p.textContent=`${item.quantity} × ${item.product_name} (${item.product_sku}) — ${money(item.line_total,o.currency)}`;$("#orderDetailBody").append(p)}const note=attentionMessage(o.reason);if(note){const p=document.createElement("p");p.className="card-warning";p.textContent=note;$("#orderDetailBody").append(p)}detail.focus()}
$("#ordersTab").addEventListener("click",()=>{panel.hidden=false;$("#productsWorkspace").hidden=true;load().catch(()=>say("Orders are temporarily unavailable."))});
$("#productsTab").addEventListener("click",()=>{panel.hidden=true;$("#productsWorkspace").hidden=false});
$("#ordersRefresh").addEventListener("click",()=>{cursor=null;load().catch(()=>say("Orders are temporarily unavailable."))});
$("#ordersMore").addEventListener("click",()=>load().catch(()=>say("Orders are temporarily unavailable.")));
$("#ordersBack").addEventListener("click",()=>{detail.hidden=true;$("#ordersTab").focus()});
for(const id of ["ordersSearch","orderStatusFilter","paymentStatusFilter","attentionFilter"])$("#"+id).addEventListener("change",()=>{cursor=null;load().catch(()=>say("Orders are temporarily unavailable."))});
